require: rubocop-rails

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Max: 50

Layout/LineLength:
  Max: 150

Style/Documentation:
  Enabled: false

Rails/FilePath:
  Enabled: false